### ISSUE TITLE
Verbetering [DO2]: probeer meer op abstracte gedrag te richten dan op technische implementatiedetails bij specificeren van features, user stories en scenario's

### ISSUE THREAD

**Issue by arothuis-hu** [Altijd-youri/cisq1-lingo#3]
https://github.com/Altijd-youri/cisq1-lingo/blob/72aecd1a8139de319e2ffa2e262c356344c9eb02/src/test/resources/features/trainer.feature#L30-L47

Probeer zonder legend te werken.
Het moet voor een specificatie meteen uit de testtabel duidelijk worden wat er wordt bedoeld.
Zie hiervoor de opdrachtbeschrijving (de voorbeeldtabel) en de slides workshop 2.

**Comment by Altijd-youri** [comment]
Fixed in commit 64f6e75
